---
- name: Disable the default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: >
    'default' not in nginx_sites.keys()
  notify:
  - reload nginx
  tags: [configuration,nginx]

- name: Remove the default configuration
  file: path=/etc/nginx/conf.d/default.conf state=absent
  when: >
    'default' not in nginx_configs.keys()
  notify:
  - reload nginx
  tags: [configuration,nginx]

