---
 - name: Install Java (dependency for logstash)
   yum: name=java-1.7.0-openjdk state=latest

 - name: Enable Logstash repository
   copy: src=logstash.repo dest=/etc/yum.repos.d/logstash.repo

 - name: Add Logstash Repo Key
   rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present

 - name: Install Logstash and Logstash-Contrib
   yum: name={{ item }} state=latest
   with_items: ['logstash', 'logstash-contrib']

 - name: Configure default settings for Logstash
   copy: src=defaults.conf dest=/etc/sysconfig/logstash owner=root group=root mode=0644 backup=yes
   notify: restart logstash

 - name: Copy Logstash Input Configuration
   copy: src=nginx.conf dest=/etc/logstash/conf.d/nginx.conf owner=root group=root mode=0644
   notify: restart logstash
